services:
  prometheus:
    image: prom/prometheus:v3.3.1
    restart: always
    networks:
      - monitoring
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  loki:
    image: grafana/loki:3.5.0
    restart: always
    networks:
      - monitoring
    volumes:
      - ./config/loki:/etc/loki:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/loki.yml

  promtail:
    image: grafana/promtail:3.5.0
    restart: always
    networks:
      - monitoring
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail:/etc/promtail:ro
    command: -config.file=/etc/promtail/promtail.yml

  grafana:
    image: grafana/grafana:12.0.0
    restart: always
    networks:
      - monitoring
      - traefik-public
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD?Variable not set}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN?Variable not set}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.grafana-http.rule=Host(`grafana.${DOMAIN?Variable not set}`)
      - traefik.http.routers.grafana-http.entrypoints=http
      - traefik.http.routers.grafana-http.middlewares=https-redirect
      - traefik.http.routers.grafana-https.rule=Host(`grafana.${DOMAIN?Variable not set}`)
      - traefik.http.routers.grafana-https.entrypoints=https
      - traefik.http.routers.grafana-https.tls=true
      - traefik.http.routers.grafana-https.tls.certresolver=le
      - traefik.http.services.grafana.loadbalancer.server.port=3000

volumes:
  prometheus-data:
  loki-data:
  grafana-data:

networks:
  monitoring:
    external: true
  traefik-public:
    external: true
