// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  GetAccountData,
  GetAccountResponse,
  GetDatasetsData,
  GetDatasetsResponse,
  LoginAccessTokenData,
  LoginAccessTokenResponse,
  TestTokenResponse,
  RecoverPasswordData,
  RecoverPasswordResponse,
  ResetPasswordData,
  ResetPasswordResponse,
  RecoverPasswordHtmlContentData,
  RecoverPasswordHtmlContentResponse,
  LoginWithGithubData,
  LoginWithGithubResponse,
  LoginWithGithubOidcData,
  LoginWithGithubOidcResponse,
  LoginWithGithubTokenData,
  LoginWithGithubTokenResponse,
  PostLoginDeviceData,
  PostLoginDeviceResponse,
  PostLoginDeviceAuthorizeData,
  PostLoginDeviceAuthorizeResponse,
  PostLoginDeviceTokenData,
  PostLoginDeviceTokenResponse,
  TestEmailData,
  TestEmailResponse,
  GetDiscountCodeData,
  GetDiscountCodeResponse,
  PostDiscountCodeData,
  PostDiscountCodeResponse,
  GetSubscriptionPlansResponse,
  GlobalSearchData,
  GlobalSearchResponse,
  GetNotificationsData,
  GetNotificationsResponse,
  MarkNotificationReadData,
  MarkNotificationReadResponse,
  MarkAllNotificationsReadResponse,
  GetUserOrgsResponse,
  GetOrgsData,
  GetOrgsResponse,
  PostOrgData,
  PostOrgResponse,
  AddOrgMemberData,
  AddOrgMemberResponse,
  PutOrgSubscriptionData,
  PutOrgSubscriptionResponse,
  GetOrgStorageData,
  GetOrgStorageResponse,
  GetOrgUsersData,
  GetOrgUsersResponse,
  GetProjectsData,
  GetProjectsResponse,
  PostProjectData,
  PostProjectResponse,
  GetOwnedProjectsData,
  GetOwnedProjectsResponse,
  GetProjectData,
  GetProjectResponse,
  PatchProjectData,
  PatchProjectResponse,
  DeleteProjectData,
  DeleteProjectResponse,
  DeleteProjectByIdData,
  DeleteProjectByIdResponse,
  GetProjectGitRepoData,
  GetProjectGitRepoResponse,
  SearchProjectRefsData,
  SearchProjectRefsResponse,
  GetProjectHistoryData,
  GetProjectHistoryResponse,
  GetProjectCommitData,
  GetProjectCommitResponse,
  GetProjectFileHistoryData,
  GetProjectFileHistoryResponse,
  GetProjectGitContentsData,
  GetProjectGitContentsResponse,
  GetProjectGitContents1Data,
  GetProjectGitContents1Response,
  GetProjectContentsData,
  GetProjectContentsResponse,
  GetProjectContents1Data,
  GetProjectContents1Response,
  PutProjectContentsData,
  PutProjectContentsResponse,
  PatchProjectContentsData,
  PatchProjectContentsResponse,
  GetProjectQuestionsData,
  GetProjectQuestionsResponse,
  PostProjectQuestionData,
  PostProjectQuestionResponse,
  GetProjectFiguresData,
  GetProjectFiguresResponse,
  PostProjectFigureData,
  PostProjectFigureResponse,
  GetProjectFigureData,
  GetProjectFigureResponse,
  GetProjectCommentsData,
  GetProjectCommentsResponse,
  PostProjectCommentData,
  PostProjectCommentResponse,
  PatchProjectCommentData,
  PatchProjectCommentResponse,
  DeleteProjectCommentData,
  DeleteProjectCommentResponse,
  PostProjectCommentReplyData,
  PostProjectCommentReplyResponse,
  GetProjectDatasetsData,
  GetProjectDatasetsResponse,
  GetProjectDatasetData,
  GetProjectDatasetResponse,
  PostProjectDatasetLabelData,
  PostProjectDatasetLabelResponse,
  PostProjectDatasetUploadData,
  PostProjectDatasetUploadResponse,
  GetProjectPublicationsData,
  GetProjectPublicationsResponse,
  PostProjectPublicationData,
  PostProjectPublicationResponse,
  PostProjectOverleafPublicationData,
  PostProjectOverleafPublicationResponse,
  PostProjectOverleafSyncData,
  PostProjectOverleafSyncResponse,
  PostProjectSyncData,
  PostProjectSyncResponse,
  GetProjectPipelineData,
  GetProjectPipelineResponse,
  GetProjectCollaboratorsData,
  GetProjectCollaboratorsResponse,
  PutProjectCollaboratorData,
  PutProjectCollaboratorResponse,
  DeleteProjectCollaboratorData,
  DeleteProjectCollaboratorResponse,
  GetProjectIssuesData,
  GetProjectIssuesResponse,
  PostProjectIssueData,
  PostProjectIssueResponse,
  PatchProjectIssueData,
  PatchProjectIssueResponse,
  GetProjectReferencesData,
  GetProjectReferencesResponse,
  GetProjectEnvironmentsData,
  GetProjectEnvironmentsResponse,
  PostProjectEnvironmentData,
  PostProjectEnvironmentResponse,
  GetProjectSoftwareData,
  GetProjectSoftwareResponse,
  GetProjectFileLocksData,
  GetProjectFileLocksResponse,
  PostProjectFileLockData,
  PostProjectFileLockResponse,
  DeleteProjectFileLockData,
  DeleteProjectFileLockResponse,
  GetProjectNotebooksData,
  GetProjectNotebooksResponse,
  GetProjectReproCheckData,
  GetProjectReproCheckResponse,
  PutProjectDevContainerData,
  PutProjectDevContainerResponse,
  GetProjectAppData,
  GetProjectAppResponse,
  GetProjectShowcaseData,
  GetProjectShowcaseResponse,
  GetProjectGithubReleasesData,
  GetProjectGithubReleasesResponse,
  PostProjectGithubReleaseData,
  PostProjectGithubReleaseResponse,
  PostProjectStatusData,
  PostProjectStatusResponse,
  PostProjectDvcFileData,
  PostProjectDvcFileResponse,
  GetProjectDvcFileData,
  GetProjectDvcFileResponse,
  PostProjectFsOpData,
  PostProjectFsOpResponse,
  PostProjectFsBatchOpData,
  PostProjectFsBatchOpResponse,
  ReadUsersData,
  ReadUsersResponse,
  CreateUserData,
  CreateUserResponse,
  GetCurrentUserResponse,
  DeleteCurrentUserResponse,
  UpdateCurrentUserData,
  UpdateCurrentUserResponse,
  UpdateCurrentUserPasswordData,
  UpdateCurrentUserPasswordResponse,
  RegisterUserData,
  RegisterUserResponse,
  ReadUserByIdData,
  ReadUserByIdResponse,
  UpdateUserData,
  UpdateUserResponse,
  DeleteUserData,
  DeleteUserResponse,
  GetUserGithubReposData,
  GetUserGithubReposResponse,
  PutUserSubscriptionData,
  PutUserSubscriptionResponse,
  GetUserTokensData,
  GetUserTokensResponse,
  PostUserTokenData,
  PostUserTokenResponse,
  PatchUserTokenData,
  PatchUserTokenResponse,
  DeleteUserTokenData,
  DeleteUserTokenResponse,
  GetUserGithubAppInstallationsResponse,
  GetUserConnectedAccountsResponse,
  PostUserZenodoAuthData,
  PostUserZenodoAuthResponse,
  GetUserZenodoTokenResponse,
  GetUserGithubTokenResponse,
  GetUserOverleafTokenResponse,
  PutUserOverleafTokenData,
  PutUserOverleafTokenResponse,
  PostUserGoogleAuthData,
  PostUserGoogleAuthResponse,
  DeleteUserExternalCredentialData,
  DeleteUserExternalCredentialResponse,
  GetUserStorageResponse,
} from "./types.gen"

export class AccountsService {
  /**
   * Get Account
   * @param data The data for the request.
   * @param data.accountName
   * @returns AccountPublic Successful Response
   * @throws ApiError
   */
  public static getAccount(
    data: GetAccountData,
  ): CancelablePromise<GetAccountResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/accounts/{account_name}",
      path: {
        account_name: data.accountName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DatasetsService {
  /**
   * Get Datasets
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.includeImported
   * @param data.searchFor
   * @returns DatasetsResponse Successful Response
   * @throws ApiError
   */
  public static getDatasets(
    data: GetDatasetsData = {},
  ): CancelablePromise<GetDatasetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/datasets",
      query: {
        limit: data.limit,
        offset: data.offset,
        include_imported: data.includeImported,
        search_for: data.searchFor,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * Get an access token for future requests.
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static accessToken(
    data: LoginAccessTokenData,
  ): CancelablePromise<LoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<TestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/test-token",
    })
  }

  /**
   * Recover Password
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: RecoverPasswordData,
  ): CancelablePromise<RecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: ResetPasswordData,
  ): CancelablePromise<ResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * Get HTML content for password recovery.
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: RecoverPasswordHtmlContentData,
  ): CancelablePromise<RecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Login With Github
   * Log in a user from GitHub authentication, creating a new account if
   * necessary.
   *
   * The response from GitHub, after parsing into a dictionary, will look
   * something like:
   *
   * ```
   * {'access_token': '...',
   * 'expires_in': '28800',
   * 'refresh_token': '...',
   * 'refresh_token_expires_in': '15897600',
   * 'scope': '',
   * 'token_type': 'bearer'}
   * ```
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static withGithub(
    data: LoginWithGithubData,
  ): CancelablePromise<LoginWithGithubResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/github",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Login With Github Oidc
   * Authenticate using an OIDC token from GitHub Actions or Codespaces.
   *
   * This endpoint validates the OIDC token from GitHub Actions or GitHub
   * Codespaces and returns a Calkit access token. The OIDC token's claims
   * are verified to ensure it's from a trusted repository.
   *
   * The token must be provided in the Authorization header as: "Bearer <token>"
   *
   * For GitHub Actions, the token should be obtained using:
   *
   * ```yaml
   * permissions:
   * id-token: write
   * ```
   *
   * For GitHub Codespaces, the token is available via the
   * ACTIONS_ID_TOKEN_REQUEST_URL environment variable.
   * @param data The data for the request.
   * @param data.authorization
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static withGithubOidc(
    data: LoginWithGithubOidcData = {},
  ): CancelablePromise<LoginWithGithubOidcResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/github-oidc",
      headers: {
        authorization: data.authorization,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Login With Github Token
   * Authenticate using a GitHub token, e.g., from a Codespace.
   * @param data The data for the request.
   * @param data.authorization
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static withGithubToken(
    data: LoginWithGithubTokenData = {},
  ): CancelablePromise<LoginWithGithubTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/github-token",
      headers: {
        authorization: data.authorization,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Login Device
   * Initiate a CLI device authorization flow.
   *
   * The CLI calls this endpoint, which returns a device_code and a URL for
   * the user to visit in their browser to authorize the CLI. The CLI then
   * polls ``/login/device/token`` with the device_code to receive the access
   * token once the user has authorized it.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns DeviceAuthResponse Successful Response
   * @throws ApiError
   */
  public static postLoginDevice(
    data: PostLoginDeviceData = {},
  ): CancelablePromise<PostLoginDeviceResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/device",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Login Device Authorize
   * Authorize a pending CLI device auth request.
   *
   * The user must be authenticated. This endpoint is called by the frontend
   * after the user has logged in and clicked "Authorize".
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static postLoginDeviceAuthorize(
    data: PostLoginDeviceAuthorizeData,
  ): CancelablePromise<PostLoginDeviceAuthorizeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/device/authorize",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Login Device Token
   * Poll for a CLI access token after device authorization.
   *
   * The CLI calls this endpoint repeatedly until it receives a token or
   * the request expires. Returns 202 while authorization is still pending.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static postLoginDeviceToken(
    data: PostLoginDeviceTokenData,
  ): CancelablePromise<PostLoginDeviceTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/login/device/token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MiscService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: TestEmailData,
  ): CancelablePromise<TestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Discount Code
   * @param data The data for the request.
   * @param data.discountCode
   * @param data.nUsers
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static getDiscountCode(
    data: GetDiscountCodeData,
  ): CancelablePromise<GetDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/discount-codes/{discount_code}",
      path: {
        discount_code: data.discountCode,
      },
      query: {
        n_users: data.nUsers,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Discount Code
   * @param data The data for the request.
   * @param data.requestBody
   * @returns DiscountCode Successful Response
   * @throws ApiError
   */
  public static postDiscountCode(
    data: PostDiscountCodeData,
  ): CancelablePromise<PostDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/discount-codes",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Subscription Plans
   * @returns SubscriptionPlan Successful Response
   * @throws ApiError
   */
  public static getSubscriptionPlans(): CancelablePromise<GetSubscriptionPlansResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/subscription-plans",
    })
  }

  /**
   * Global Search
   * Search projects, orgs, and datasets visible to the current user.
   *
   * Parameters
   * ----------
   * q:
   * Query string matched case-insensitively against names, titles,
   * and descriptions. Short queries (<2 chars) return no results.
   * limit:
   * Maximum number of results returned per category.
   * @param data The data for the request.
   * @param data.q
   * @param data.limit
   * @returns SearchResults Successful Response
   * @throws ApiError
   */
  public static globalSearch(
    data: GlobalSearchData,
  ): CancelablePromise<GlobalSearchResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/search",
      query: {
        q: data.q,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Notifications
   * @param data The data for the request.
   * @param data.unreadOnly
   * @returns Notification Successful Response
   * @throws ApiError
   */
  public static getNotifications(
    data: GetNotificationsData = {},
  ): CancelablePromise<GetNotificationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/notifications",
      query: {
        unread_only: data.unreadOnly,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Mark Notification Read
   * @param data The data for the request.
   * @param data.notificationId
   * @returns Notification Successful Response
   * @throws ApiError
   */
  public static markNotificationRead(
    data: MarkNotificationReadData,
  ): CancelablePromise<MarkNotificationReadResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/notifications/{notification_id}/read",
      path: {
        notification_id: data.notificationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Mark All Notifications Read
   * @returns void Successful Response
   * @throws ApiError
   */
  public static markAllNotificationsRead(): CancelablePromise<MarkAllNotificationsReadResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/notifications/read-all",
    })
  }
}

export class OrgsService {
  /**
   * Get User Orgs
   * @returns OrgPublic Successful Response
   * @throws ApiError
   */
  public static getUserOrgs(): CancelablePromise<GetUserOrgsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/orgs",
    })
  }

  /**
   * Get Orgs
   * Get a list of orgs.
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.searchFor
   * @returns OrgsResponse Successful Response
   * @throws ApiError
   */
  public static getOrgs(
    data: GetOrgsData = {},
  ): CancelablePromise<GetOrgsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/orgs",
      query: {
        limit: data.limit,
        offset: data.offset,
        search_for: data.searchFor,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Org
   * @param data The data for the request.
   * @param data.requestBody
   * @returns OrgPublic Successful Response
   * @throws ApiError
   */
  public static postOrg(data: PostOrgData): CancelablePromise<PostOrgResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/orgs",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Add Org Member
   * @param data The data for the request.
   * @param data.orgName
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static addOrgMember(
    data: AddOrgMemberData,
  ): CancelablePromise<AddOrgMemberResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/orgs/{org_name}/members",
      path: {
        org_name: data.orgName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Put Org Subscription
   * @param data The data for the request.
   * @param data.orgName
   * @param data.requestBody
   * @returns UpdateSubscriptionResponse Successful Response
   * @throws ApiError
   */
  public static putOrgSubscription(
    data: PutOrgSubscriptionData,
  ): CancelablePromise<PutOrgSubscriptionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/orgs/{org_name}/subscription",
      path: {
        org_name: data.orgName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Org Storage
   * @param data The data for the request.
   * @param data.orgName
   * @returns StorageUsage Successful Response
   * @throws ApiError
   */
  public static getOrgStorage(
    data: GetOrgStorageData,
  ): CancelablePromise<GetOrgStorageResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/orgs/{org_name}/storage",
      path: {
        org_name: data.orgName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Org Users
   * @param data The data for the request.
   * @param data.orgName
   * @returns OrgUserPublic Successful Response
   * @throws ApiError
   */
  public static getOrgUsers(
    data: GetOrgUsersData,
  ): CancelablePromise<GetOrgUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/orgs/{org_name}/users",
      path: {
        org_name: data.orgName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ProjectsService {
  /**
   * Get Projects
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.searchFor
   * @param data.ownerName
   * @returns ProjectsPublic Successful Response
   * @throws ApiError
   */
  public static getProjects(
    data: GetProjectsData = {},
  ): CancelablePromise<GetProjectsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects",
      query: {
        limit: data.limit,
        offset: data.offset,
        search_for: data.searchFor,
        owner_name: data.ownerName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project
   * Create new project.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ProjectPublic Successful Response
   * @throws ApiError
   */
  public static postProject(
    data: PostProjectData,
  ): CancelablePromise<PostProjectResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Owned Projects
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.searchFor
   * @returns ProjectsPublic Successful Response
   * @throws ApiError
   */
  public static getOwnedProjects(
    data: GetOwnedProjectsData = {},
  ): CancelablePromise<GetOwnedProjectsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/projects",
      query: {
        limit: data.limit,
        offset: data.offset,
        search_for: data.searchFor,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.getExtendedInfo
   * @param data.ref
   * @returns ProjectOptionalExtended Successful Response
   * @throws ApiError
   */
  public static getProject(
    data: GetProjectData,
  ): CancelablePromise<GetProjectResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        get_extended_info: data.getExtendedInfo,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch Project
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns ProjectPublic Successful Response
   * @throws ApiError
   */
  public static patchProject(
    data: PatchProjectData,
  ): CancelablePromise<PatchProjectResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/projects/{owner_name}/{project_name}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProject(
    data: DeleteProjectData,
  ): CancelablePromise<DeleteProjectResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/projects/{owner_name}/{project_name}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project By Id
   * @param data The data for the request.
   * @param data.projectId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProjectById(
    data: DeleteProjectByIdData,
  ): CancelablePromise<DeleteProjectByIdResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/projects/{project_id}",
      path: {
        project_id: data.projectId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Git Repo
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectGitRepo(
    data: GetProjectGitRepoData,
  ): CancelablePromise<GetProjectGitRepoResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/repo",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Search Project Refs
   * Get git refs (branches, tags, commits) in a project.
   *
   * Parameters
   * ----------
   * owner_name:
   * Owner of the project.
   * project_name:
   * Name of the project.
   * q:
   * Optional search query to filter refs by branch name, tag name,
   * commit message, or author.
   *
   * Returns
   * -------
   * list[GitRef]
   * List of matching GitRef objects with name, kind, message, author,
   * timestamp.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.q Search query for refs
   * @returns GitRef Successful Response
   * @throws ApiError
   */
  public static searchProjectRefs(
    data: SearchProjectRefsData,
  ): CancelablePromise<SearchProjectRefsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/refs",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        q: data.q,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project History
   * Get paginated git commit history for a project.
   *
   * Parameters
   * ----------
   * limit:
   * Maximum number of commits to return.
   * offset:
   * Number of commits to skip from the newest commit.
   * ref:
   * Optional branch, tag, or commit to read history from.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.limit Max number of commits to return
   * @param data.offset Number of commits to skip
   * @param data.ref Branch, tag, or commit to read history from
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectHistory(
    data: GetProjectHistoryData,
  ): CancelablePromise<GetProjectHistoryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/history",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        limit: data.limit,
        offset: data.offset,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Commit
   * Get details for a specific commit including changed files.
   *
   * Parameters
   * ----------
   * commit_hash:
   * Full or short commit hash to inspect.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.commitHash
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectCommit(
    data: GetProjectCommitData,
  ): CancelablePromise<GetProjectCommitResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/commits/{commit_hash}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        commit_hash: data.commitHash,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project File History
   * Get git commit history for a specific file path.
   *
   * Returns commits that touched the file directly, its DVC pointer (.dvc),
   * or dvc.lock (for pipeline outputs), so DVC-tracked artifacts are covered.
   * Pass ``storage`` when the caller knows the artifact's storage class so
   * irrelevant lookups are skipped.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.limit Max number of commits to return
   * @param data.storage Artifact storage class; when supplied, limits the lookup to relevant sources (e.g., skips the dvc.lock scan for git files).
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectFileHistory(
    data: GetProjectFileHistoryData,
  ): CancelablePromise<GetProjectFileHistoryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/file-history",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        path: data.path,
        limit: data.limit,
        storage: data.storage,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Git Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.astype
   * @param data.ref
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectGitContents(
    data: GetProjectGitContentsData,
  ): CancelablePromise<GetProjectGitContentsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/contents",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        path: data.path,
        astype: data.astype,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Git Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.astype
   * @param data.ref
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectGitContents1(
    data: GetProjectGitContents1Data,
  ): CancelablePromise<GetProjectGitContents1Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/git/contents/{path}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        path: data.path,
      },
      query: {
        astype: data.astype,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.ttl
   * @param data.ref
   * @returns ContentsItem Successful Response
   * @throws ApiError
   */
  public static getProjectContents(
    data: GetProjectContentsData,
  ): CancelablePromise<GetProjectContentsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/contents",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        path: data.path,
        ttl: data.ttl,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.ttl
   * @param data.ref
   * @returns ContentsItem Successful Response
   * @throws ApiError
   */
  public static getProjectContents1(
    data: GetProjectContents1Data,
  ): CancelablePromise<GetProjectContents1Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/contents/{path}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        path: data.path,
      },
      query: {
        ttl: data.ttl,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Put Project Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.contentLength
   * @param data.formData
   * @returns ContentsItem Successful Response
   * @throws ApiError
   */
  public static putProjectContents(
    data: PutProjectContentsData,
  ): CancelablePromise<PutProjectContentsResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/projects/{owner_name}/{project_name}/contents/{path}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        path: data.path,
      },
      headers: {
        "content-length": data.contentLength,
      },
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch Project Contents
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.path
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static patchProjectContents(
    data: PatchProjectContentsData,
  ): CancelablePromise<PatchProjectContentsResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/projects/{owner_name}/{project_name}/contents/{path}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        path: data.path,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Questions
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Question Successful Response
   * @throws ApiError
   */
  public static getProjectQuestions(
    data: GetProjectQuestionsData,
  ): CancelablePromise<GetProjectQuestionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/questions",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Question
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns Question Successful Response
   * @throws ApiError
   */
  public static postProjectQuestion(
    data: PostProjectQuestionData,
  ): CancelablePromise<PostProjectQuestionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/questions",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Figures
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Figure Successful Response
   * @throws ApiError
   */
  public static getProjectFigures(
    data: GetProjectFiguresData,
  ): CancelablePromise<GetProjectFiguresResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/figures",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Figure
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.formData
   * @returns Figure Successful Response
   * @throws ApiError
   */
  public static postProjectFigure(
    data: PostProjectFigureData,
  ): CancelablePromise<PostProjectFigureResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/figures",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Figure
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.figurePath
   * @param data.ttl
   * @param data.ref
   * @returns Figure Successful Response
   * @throws ApiError
   */
  public static getProjectFigure(
    data: GetProjectFigureData,
  ): CancelablePromise<GetProjectFigureResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/figures/{figure_path}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        figure_path: data.figurePath,
      },
      query: {
        ttl: data.ttl,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Comments
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.artifactType
   * @param data.artifactPath
   * @returns ProjectComment Successful Response
   * @throws ApiError
   */
  public static getProjectComments(
    data: GetProjectCommentsData,
  ): CancelablePromise<GetProjectCommentsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/comments",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        artifact_type: data.artifactType,
        artifact_path: data.artifactPath,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Comment
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns ProjectComment Successful Response
   * @throws ApiError
   */
  public static postProjectComment(
    data: PostProjectCommentData,
  ): CancelablePromise<PostProjectCommentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/comments",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch Project Comment
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.commentId
   * @param data.requestBody
   * @returns ProjectComment Successful Response
   * @throws ApiError
   */
  public static patchProjectComment(
    data: PatchProjectCommentData,
  ): CancelablePromise<PatchProjectCommentResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/projects/{owner_name}/{project_name}/comments/{comment_id}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        comment_id: data.commentId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project Comment
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.commentId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteProjectComment(
    data: DeleteProjectCommentData,
  ): CancelablePromise<DeleteProjectCommentResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/projects/{owner_name}/{project_name}/comments/{comment_id}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        comment_id: data.commentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Comment Reply
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.commentId
   * @param data.requestBody
   * @returns ProjectComment Successful Response
   * @throws ApiError
   */
  public static postProjectCommentReply(
    data: PostProjectCommentReplyData,
  ): CancelablePromise<PostProjectCommentReplyResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/comments/{comment_id}/replies",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        comment_id: data.commentId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Datasets
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Dataset Successful Response
   * @throws ApiError
   */
  public static getProjectDatasets(
    data: GetProjectDatasetsData,
  ): CancelablePromise<GetProjectDatasetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/datasets",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Dataset
   * @param data The data for the request.
   * @param data.path
   * @param data.ownerName
   * @param data.projectName
   * @param data.filterPaths
   * @param data.ref
   * @returns DatasetForImport Successful Response
   * @throws ApiError
   */
  public static getProjectDataset(
    data: GetProjectDatasetData,
  ): CancelablePromise<GetProjectDatasetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/datasets/{path}",
      path: {
        path: data.path,
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        filter_paths: data.filterPaths,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Dataset Label
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns Dataset Successful Response
   * @throws ApiError
   */
  public static postProjectDatasetLabel(
    data: PostProjectDatasetLabelData,
  ): CancelablePromise<PostProjectDatasetLabelResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/datasets/label",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Dataset Upload
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.contentLength
   * @param data.formData
   * @returns Dataset Successful Response
   * @throws ApiError
   */
  public static postProjectDatasetUpload(
    data: PostProjectDatasetUploadData,
  ): CancelablePromise<PostProjectDatasetUploadResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/datasets/upload",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      headers: {
        "content-length": data.contentLength,
      },
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Publications
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Publication Successful Response
   * @throws ApiError
   */
  public static getProjectPublications(
    data: GetProjectPublicationsData,
  ): CancelablePromise<GetProjectPublicationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/publications",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Publication
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.formData
   * @returns Publication Successful Response
   * @throws ApiError
   */
  public static postProjectPublication(
    data: PostProjectPublicationData,
  ): CancelablePromise<PostProjectPublicationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/publications",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Overleaf Publication
   * Import a publication from Overleaf into a project.
   *
   * Supports two modes:
   * 1. Import and link via cloning the Overleaf Git repo.
   * Requires an Overleaf token and performs sync setup.
   * 2. Import ZIP via user-provided downloaded archive.
   * Skips linkage and sync info; just copies files into repo.
   *
   * Accepts multipart/form-data with an optional 'file' field
   * (for the ZIP archive).
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.formData
   * @returns Publication Successful Response
   * @throws ApiError
   */
  public static postProjectOverleafPublication(
    data: PostProjectOverleafPublicationData,
  ): CancelablePromise<PostProjectOverleafPublicationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/publications/overleaf",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Overleaf Sync
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns OverleafSyncResponse Successful Response
   * @throws ApiError
   */
  public static postProjectOverleafSync(
    data: PostProjectOverleafSyncData,
  ): CancelablePromise<PostProjectOverleafSyncResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/overleaf-syncs",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Sync
   * Synchronize a project with its Git repo.
   *
   * Do we actually need this? It will give us a way to operate if GitHub is
   * down, at least in read-only mode.
   * Or perhaps we can bidirectionally sync, allowing users to update Calkit
   * entities and we'll commit them back on sync.
   * It would probably be better to use Git for that, so we can handle
   * asynchronous edits with merges.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static postProjectSync(
    data: PostProjectSyncData,
  ): CancelablePromise<PostProjectSyncResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/syncs",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Pipeline
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectPipeline(
    data: GetProjectPipelineData,
  ): CancelablePromise<GetProjectPipelineResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/pipeline",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Collaborators
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns Collaborator Successful Response
   * @throws ApiError
   */
  public static getProjectCollaborators(
    data: GetProjectCollaboratorsData,
  ): CancelablePromise<GetProjectCollaboratorsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/collaborators",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Put Project Collaborator
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.githubUsername
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static putProjectCollaborator(
    data: PutProjectCollaboratorData,
  ): CancelablePromise<PutProjectCollaboratorResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/projects/{owner_name}/{project_name}/collaborators/{github_username}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        github_username: data.githubUsername,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project Collaborator
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.githubUsername
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProjectCollaborator(
    data: DeleteProjectCollaboratorData,
  ): CancelablePromise<DeleteProjectCollaboratorResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/projects/{owner_name}/{project_name}/collaborators/{github_username}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        github_username: data.githubUsername,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Issues
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.page
   * @param data.perPage
   * @param data.state
   * @returns Issue Successful Response
   * @throws ApiError
   */
  public static getProjectIssues(
    data: GetProjectIssuesData,
  ): CancelablePromise<GetProjectIssuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/issues",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        page: data.page,
        per_page: data.perPage,
        state: data.state,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Issue
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns Issue Successful Response
   * @throws ApiError
   */
  public static postProjectIssue(
    data: PostProjectIssueData,
  ): CancelablePromise<PostProjectIssueResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/issues",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch Project Issue
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.issueNumber
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static patchProjectIssue(
    data: PatchProjectIssueData,
  ): CancelablePromise<PatchProjectIssueResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/projects/{owner_name}/{project_name}/issues/{issue_number}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        issue_number: data.issueNumber,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project References
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns References Successful Response
   * @throws ApiError
   */
  public static getProjectReferences(
    data: GetProjectReferencesData,
  ): CancelablePromise<GetProjectReferencesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/references",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Environments
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Environment Successful Response
   * @throws ApiError
   */
  public static getProjectEnvironments(
    data: GetProjectEnvironmentsData,
  ): CancelablePromise<GetProjectEnvironmentsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/environments",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Environment
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @param data.ref
   * @returns Environment Successful Response
   * @throws ApiError
   */
  public static postProjectEnvironment(
    data: PostProjectEnvironmentData,
  ): CancelablePromise<PostProjectEnvironmentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/environments",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Software
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Software Successful Response
   * @throws ApiError
   */
  public static getProjectSoftware(
    data: GetProjectSoftwareData,
  ): CancelablePromise<GetProjectSoftwareResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/software",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project File Locks
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns FileLock Successful Response
   * @throws ApiError
   */
  public static getProjectFileLocks(
    data: GetProjectFileLocksData,
  ): CancelablePromise<GetProjectFileLocksResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/file-locks",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project File Lock
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns FileLock Successful Response
   * @throws ApiError
   */
  public static postProjectFileLock(
    data: PostProjectFileLockData,
  ): CancelablePromise<PostProjectFileLockResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/file-locks",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Project File Lock
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteProjectFileLock(
    data: DeleteProjectFileLockData,
  ): CancelablePromise<DeleteProjectFileLockResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/projects/{owner_name}/{project_name}/file-locks",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Notebooks
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns Notebook Successful Response
   * @throws ApiError
   */
  public static getProjectNotebooks(
    data: GetProjectNotebooksData,
  ): CancelablePromise<GetProjectNotebooksResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/notebooks",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Repro Check
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns ReproCheck Successful Response
   * @throws ApiError
   */
  public static getProjectReproCheck(
    data: GetProjectReproCheckData,
  ): CancelablePromise<GetProjectReproCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/repro-check",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Put Project Dev Container
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static putProjectDevContainer(
    data: PutProjectDevContainerData,
  ): CancelablePromise<PutProjectDevContainerResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/projects/{owner_name}/{project_name}/devcontainer",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project App
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ref
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectApp(
    data: GetProjectAppData,
  ): CancelablePromise<GetProjectAppResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/app",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Showcase
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.ttl
   * @param data.ref
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectShowcase(
    data: GetProjectShowcaseData,
  ): CancelablePromise<GetProjectShowcaseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/showcase",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      query: {
        ttl: data.ttl,
        ref: data.ref,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Github Releases
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @returns GitHubRelease Successful Response
   * @throws ApiError
   */
  public static getProjectGithubReleases(
    data: GetProjectGithubReleasesData,
  ): CancelablePromise<GetProjectGithubReleasesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/github-releases",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Github Release
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns GitHubRelease Successful Response
   * @throws ApiError
   */
  public static postProjectGithubRelease(
    data: PostProjectGithubReleaseData,
  ): CancelablePromise<PostProjectGithubReleaseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/github-releases",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Status
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns ProjectStatus Successful Response
   * @throws ApiError
   */
  public static postProjectStatus(
    data: PostProjectStatusData,
  ): CancelablePromise<PostProjectStatusResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/status",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Dvc File
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.idx
   * @param data.md5
   * @param data.scope
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static postProjectDvcFile(
    data: PostProjectDvcFileData,
  ): CancelablePromise<PostProjectDvcFileResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/dvc/files/md5/{idx}/{md5}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        idx: data.idx,
        md5: data.md5,
      },
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Project Dvc File
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.idx
   * @param data.md5
   * @param data.scope
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getProjectDvcFile(
    data: GetProjectDvcFileData,
  ): CancelablePromise<GetProjectDvcFileResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/projects/{owner_name}/{project_name}/dvc/files/md5/{idx}/{md5}",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
        idx: data.idx,
        md5: data.md5,
      },
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Fs Op
   * Endpoint for the fsspec client to know how to perform operations on a
   * given path within the project.
   *
   * The client specifies the operation (get/put) and path, and the server
   * responds with instructions on how to access it:
   * - Presigned URL for direct HTTP access
   * - API credentials for indirect API access
   * - Request delegation info for non-presigned flows
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns FsOpResponse Successful Response
   * @throws ApiError
   */
  public static postProjectFsOp(
    data: PostProjectFsOpData,
  ): CancelablePromise<PostProjectFsOpResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/fs/ops",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post Project Fs Batch Op
   * Endpoint for batch file system operations for multiple paths.
   * @param data The data for the request.
   * @param data.ownerName
   * @param data.projectName
   * @param data.requestBody
   * @returns FsOpBatchResponse Successful Response
   * @throws ApiError
   */
  public static postProjectFsBatchOp(
    data: PostProjectFsBatchOpData,
  ): CancelablePromise<PostProjectFsBatchOpResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/projects/{owner_name}/{project_name}/fs/ops/batch",
      path: {
        owner_name: data.ownerName,
        project_name: data.projectName,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: ReadUsersData = {},
  ): CancelablePromise<ReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/users",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: CreateUserData,
  ): CancelablePromise<CreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/users",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Current User
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static getCurrentUser(): CancelablePromise<GetCurrentUserResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user",
    })
  }

  /**
   * Delete Current User
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCurrentUser(): CancelablePromise<DeleteCurrentUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/user",
    })
  }

  /**
   * Update Current User
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateCurrentUser(
    data: UpdateCurrentUserData,
  ): CancelablePromise<UpdateCurrentUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/user",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Current User Password
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updateCurrentUserPassword(
    data: UpdateCurrentUserPasswordData,
  ): CancelablePromise<UpdateCurrentUserPasswordResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/user/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: RegisterUserData,
  ): CancelablePromise<RegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by ID.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: ReadUserByIdData,
  ): CancelablePromise<ReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UpdateUserData,
  ): CancelablePromise<UpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: DeleteUserData,
  ): CancelablePromise<DeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Github Repos
   * @param data The data for the request.
   * @param data.perPage
   * @param data.page
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getUserGithubRepos(
    data: GetUserGithubReposData = {},
  ): CancelablePromise<GetUserGithubReposResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/github/repos",
      query: {
        per_page: data.perPage,
        page: data.page,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Put User Subscription
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UpdateSubscriptionResponse Successful Response
   * @throws ApiError
   */
  public static putUserSubscription(
    data: PutUserSubscriptionData,
  ): CancelablePromise<PutUserSubscriptionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/user/subscription",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Tokens
   * @param data The data for the request.
   * @param data.isActive
   * @returns UserTokenPublic Successful Response
   * @throws ApiError
   */
  public static getUserTokens(
    data: GetUserTokensData = {},
  ): CancelablePromise<GetUserTokensResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/tokens",
      query: {
        is_active: data.isActive,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post User Token
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TokenResp Successful Response
   * @throws ApiError
   */
  public static postUserToken(
    data: PostUserTokenData,
  ): CancelablePromise<PostUserTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/user/tokens",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch User Token
   * @param data The data for the request.
   * @param data.tokenId
   * @param data.requestBody
   * @returns UserTokenPublic Successful Response
   * @throws ApiError
   */
  public static patchUserToken(
    data: PatchUserTokenData,
  ): CancelablePromise<PatchUserTokenResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/user/tokens/{token_id}",
      path: {
        token_id: data.tokenId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User Token
   * @param data The data for the request.
   * @param data.tokenId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserToken(
    data: DeleteUserTokenData,
  ): CancelablePromise<DeleteUserTokenResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/user/tokens/{token_id}",
      path: {
        token_id: data.tokenId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Github App Installations
   * @returns GitHubInstallations Successful Response
   * @throws ApiError
   */
  public static getUserGithubAppInstallations(): CancelablePromise<GetUserGithubAppInstallationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/github-app-installations",
    })
  }

  /**
   * Get User Connected Accounts
   * @returns ConnectedAccounts Successful Response
   * @throws ApiError
   */
  public static getUserConnectedAccounts(): CancelablePromise<GetUserConnectedAccountsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/connected-accounts",
    })
  }

  /**
   * Post User Zenodo Auth
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static postUserZenodoAuth(
    data: PostUserZenodoAuthData,
  ): CancelablePromise<PostUserZenodoAuthResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/user/zenodo-auth",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Zenodo Token
   * @returns ExternalTokenResponse Successful Response
   * @throws ApiError
   */
  public static getUserZenodoToken(): CancelablePromise<GetUserZenodoTokenResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/zenodo-token",
    })
  }

  /**
   * Get User Github Token
   * @returns ExternalTokenResponse Successful Response
   * @throws ApiError
   */
  public static getUserGithubToken(): CancelablePromise<GetUserGithubTokenResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/github-token",
    })
  }

  /**
   * Get User Overleaf Token
   * @returns ExternalTokenResponse Successful Response
   * @throws ApiError
   */
  public static getUserOverleafToken(): CancelablePromise<GetUserOverleafTokenResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/overleaf-token",
    })
  }

  /**
   * Put User Overleaf Token
   * Update the current user's Overleaf token.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static putUserOverleafToken(
    data: PutUserOverleafTokenData,
  ): CancelablePromise<PutUserOverleafTokenResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/user/overleaf-token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Post User Google Auth
   * Authenticate with Google using authorization code.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static postUserGoogleAuth(
    data: PostUserGoogleAuthData,
  ): CancelablePromise<PostUserGoogleAuthResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/user/google-auth",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User External Credential
   * Disconnect an external account by deleting its credential.
   * @param data The data for the request.
   * @param data.provider
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserExternalCredential(
    data: DeleteUserExternalCredentialData,
  ): CancelablePromise<DeleteUserExternalCredentialResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/user/external-credentials/{provider}",
      path: {
        provider: data.provider,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Storage
   * @returns StorageUsage Successful Response
   * @throws ApiError
   */
  public static getUserStorage(): CancelablePromise<GetUserStorageResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/user/storage",
    })
  }
}
