"""Add release github issue url and comment threading

Revision ID: 026f9b3efef9
Revises: 69f55a987c11
Create Date: 2026-06-26 15:31:03.432370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '026f9b3efef9'
down_revision = '69f55a987c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('github_issue_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('releasecomment', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_releasecomment_parent_id', 'releasecomment', 'releasecomment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_releasecomment_parent_id', 'releasecomment', type_='foreignkey')
    op.drop_column('releasecomment', 'parent_id')
    op.drop_column('release', 'github_issue_url')
    # ### end Alembic commands ###
