"""Add fields to publication comment, figure comment, notification table

Revision ID: 4fd2570919f9
Revises: cfba4c950850
Create Date: 2026-03-31 15:04:43.323682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fd2570919f9'
down_revision = 'cfba4c950850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('read', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('figurecomment', sa.Column('resolved', sa.DateTime(), nullable=True))
    op.add_column('publicationcomment', sa.Column('resolved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicationcomment', 'resolved')
    op.drop_column('figurecomment', 'resolved')
    op.drop_table('notification')
    # ### end Alembic commands ###
