"""Add release_viewer table

Revision ID: 69f55a987c11
Revises: aabd30a6b15b
Create Date: 2026-06-26 03:02:20.005447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69f55a987c11'
down_revision = 'aabd30a6b15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releaseviewer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('share_token_id', sa.Uuid(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_token_id'], ['releasesharetoken.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'share_token_id', name='uq_releaseviewer_release_token'),
    sa.UniqueConstraint('release_id', 'user_id', name='uq_releaseviewer_release_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releaseviewer')
    # ### end Alembic commands ###
