"""Cascade deletes for project properties

Revision ID: 721e990698b7
Revises: 7cacee34034c
Create Date: 2024-12-18 20:37:37.899008

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '721e990698b7'
down_revision = '7cacee34034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
