"""Add release comments_resolved

Revision ID: a80ecaf727ed
Revises: 026f9b3efef9
Create Date: 2026-06-26 16:07:59.654555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a80ecaf727ed'
down_revision = '026f9b3efef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('comments_resolved', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'comments_resolved')
    # ### end Alembic commands ###
