"""Add feature_vote table

Revision ID: aabd30a6b15b
Revises: afa35dae8954
Create Date: 2026-06-24 13:21:33.297343

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aabd30a6b15b'
down_revision = 'afa35dae8954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featurevote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature', name='featurevote_user_id_feature_key')
    )
    op.create_index(op.f('ix_featurevote_feature'), 'featurevote', ['feature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featurevote_feature'), table_name='featurevote')
    op.drop_table('featurevote')
    # ### end Alembic commands ###
