"""Add publication comments table

Revision ID: cfba4c950850
Revises: e1b0fa2a6d34
Create Date: 2026-03-31 14:24:40.140849

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfba4c950850'
down_revision = 'e1b0fa2a6d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicationcomment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('publication_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('highlight', sa.JSON(), nullable=True),
    sa.Column('git_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicationcomment')
    # ### end Alembic commands ###
