name: Test

on:
  pull_request:

env:
  POSTGRES_PASSWORD: test-password-for-ci
  MINIO_ROOT_PASSWORD: test-password-for-ci
  FIRST_SUPERUSER_GITHUB_USERNAME: test-user-for-ci
  FIRST_SUPERUSER_PASSWORD: test-password-for-ci
  SECRET_KEY: test-secret-key-for-ci
  FERNET_KEY: test-fernet-key-for-ci
  FERNET_KEYS: test-fernet-key-for-ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cp .env.example .env
      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d
      - name: Lint
        run: docker compose exec -T backend bash /app/scripts/lint.sh
      - name: Run tests
        run: docker compose exec -T backend bash /app/tests-start.sh "Coverage for ${{ github.sha }}"
      - name: Tear down
        if: always()
        run: docker compose down -v --remove-orphans
      - name: Store coverage files
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html
          path: backend/htmlcov

  # https://github.com/marketplace/actions/alls-green#why
  alls-green: # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
